import LoginForm from "@/app/login/LoginForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Log In | Complex blog",
  description: "The best place to post content generated by you",
};

export default function Signup() {
  return (
    <div className="h-screen w-screen grid content-center gap-4 justify-center items-center">
      <LoginForm />
    </div>
  );
}
