import PostsContextProvider from '@/Contexts/PostController'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Welcome to the world of gumball',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PostsContextProvider >
        {children}
        </PostsContextProvider >
      </body>
    </html>
  )
}
