import AdminForm from "@/app/admin/AdminForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Log In | Complex blog",
  description: "The best place to post content generated by you",
};

export default function Admin() {
  return (
    <div className="h-screen w-screen grid content-center gap-4 justify-center items-center">
      <AdminForm />
    </div>
  );
}
