import SignUpForm from "@/components/SignUpForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Signup | Complex blog",
  description: "The best place to post content generated by you"
}

export default function SignUp() {
  return (
    <div className="h-screen w-screen grid content-center gap-4 justify-center items-center">
      <SignUpForm />
    </div>
  )
}